# Generated by Django 2.2.7 on 2019-12-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_title', models.CharField(max_length=100, verbose_name='Название рецепта')),
                ('receipt_text', models.TextField(verbose_name='Текст рецепта')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author_name', models.CharField(max_length=60, verbose_name='Имя автора')),
                ('receipt_calories', models.IntegerField(verbose_name='Калорийность блюда')),
                ('receipt_products', models.TextField(verbose_name='Продукты')),
                ('receipt_kitchen', models.CharField(max_length=100, verbose_name='Кухня')),
                ('receipt_img', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=60, verbose_name='Имя автора')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.Receipt')),
            ],
        ),
    ]
