# Generated by Django 2.2.7 on 2020-01-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0002_auto_20200105_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Имя автора'),
        ),
    ]
