# Generated by Django 2.2.7 on 2020-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0004_auto_20200105_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
