# Generated by Django 2.2.7 on 2020-01-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0005_auto_20200105_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
