# Generated by Django 2.2.7 on 2020-01-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
        ('Receipts', '0007_auto_20200106_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menu.Menu'),
        ),
    ]
