# Generated by Django 2.2.7 on 2020-01-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0008_profile_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
