# Generated by Django 2.2.7 on 2020-01-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100, verbose_name='Название рецепта')),
                ('video_desc', models.TextField(verbose_name='Текст рецепта')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('video_video', models.FilePathField(verbose_name='Ссылка для видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=60, verbose_name='Имя автора')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master_class.Video')),
            ],
            options={
                'verbose_name': 'Видео комментарий',
                'verbose_name_plural': 'Видео комментарии',
            },
        ),
    ]
