# Generated by Django 2.2.7 on 2020-01-05 19:47

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master_class', '0002_auto_20200105_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
